### ISSUE TITLE
Make this work with pre-commit

### ISSUE THREAD

**Issue by lagerfeuer** [Findus23/pyLanguagetool#49]
It would be awesome to be able to add this tool to pre-commit hooks. Any plans on adding this?

See https://pre-commit.com/#new-hooks.

**Comment by Roald87** [comment]
I thought this would be easy, but I can't make it work. 

I added a `.pre-commit-hooks.yaml` to my fork of this repo and filled it with:
```yaml
- id: pylanguagetool
  name: Spellcheck with Languagetool
  description: Checks the spelling
  entry: pylanguagetool 
  language: python
```
Then I ran the pre-commits with `$pre-commit try-repo ../pyLanguagetool pylanguagetool --verbose --files path/to/some/markdown/file`

I get the following error

```
Spellcheck with Languagetool.............................................Failed
- hook id: pylanguagetool
- duration: 0.25s
- exit code: 2

usage: pylanguagetool
       [-h]
       [-V]
       [-v]
       [-a API_URL]
       [--no-color]
       [-c]
       [-s]
       [-t {txt,html,md,markdown,rst,ipynb,json,xliff}]
       [-u]
       [-r]
       [--rule-categories]
       [-l LANG]
       [-m MOTHER_TONGUE]
       [-p PREFERRED_VARIANTS]
       [-e ENABLED_RULES]
       [-d DISABLED_RULES]
       [--enabled-categories ENABLED_CATEGORIES]
       [--disabled-categories DISABLED_CATEGORIES]
       [--enabled-only]
       [--picky]
       [--pwl PWL]
       [input file]
input file is required
```
Even if I try to pass a file directly by adjusting `entry: pylanguagetool -- path/to/some/markdown/file` in `pre-commit-hooks.yaml`, I get still get an error.

```
pylanguagetool: error: unrecognized arguments: path/to/some/markdown/file
```

Guess its not so easy :/

**Comment by Findus23** [comment]
Okay, that really confused me, but I found the reason:
Printing `sys.argv` shows that pre-commit properly calls pylanguagetool and the issue is therefore unrelated to it:
 `['/tmp/tmpj_q068oy/repo1uikxb3t/py_env-python3.11/bin/pylanguagetool', 'main.txt']`

It turns out 2017 me didn't think this code block through:
https://github.com/Findus23/pyLanguagetool/blob/b59d3f46ed937f6c619bcc082d4ecb0afa63d8b0/pylanguagetool/cli.py#L101-L126

The `if not sys.stdin.isatty()` section is so that `echo "this is an test" | pylanguagetool` also works without an input file by instead reading stdin. But the way pre-commit calls pylanguagetool also triggers this.

So with https://github.com/Findus23/pyLanguagetool/commit/63ac99735323f8c27bb9d36b971be1f5a5ba0581 pylanguagetool will now only read from stdin if no input file has been specified.

With this, the rest should be possible now. Please report back if there are issues and if not, I can release a new version.


BTW, in case you are planning to use languagetool in an automated way, I would strongly recommend pointing it to [your own languagetool server](https://dev.languagetool.org/http-server) and not hitting the main https://languagetool.org/ one with requests.

**Comment by Roald87** [comment]
I made it work by cloning the latest version of the repo and adding the following `.pre-commit-hooks.yaml` file to the pylanguagetool repo

```yaml
- id: pylanguagetool
  name: Spellcheck with Languagetool
  description: Checks the spelling
  entry: pylanguagetool
  additional_dependencies:
    - markdown2
    - beautifulsoup4
  language: python

```
then I ran it with

`pre-commit try-repo ../pyLanguagetool pylanguagetool --verbose --files some/file.md`

That worked.

What didn't work was if I add this to my `pre-commit-config.yaml` in the repo where I want to add Languagetool to.

```yaml
  - repo: local
    hooks:
      - id: pylanguagetool
        files: '.*\.(md|markdown)'
        name: Languagetool spellcheck
        entry: pylanguagetool --input-type md -v
        language: python
        additional_dependencies: [pylanguagetool, beautifulsoup4, markdown2]
```

But I guess this doesn't work because this doesn't take the latest commit, but the latest release instead?

**Comment by Roald87** [comment]
The pre-commit works with my fork https://github.com/Roald87/pyLanguagetool

I added the following to my `.pre-commit-config.yaml` in another repo

```yaml
  - repo: https://github.com/Roald87/pyLanguagetool
    rev: 2cd8080
    hooks:
      - id: pylanguagetool
        files: '.*\.(md|markdown)'
        name: Languagetool spellcheck
        entry: pylanguagetool --input-type markdown
```

It works for a single file, but not if I try to run it on multiple files. I then get the error `pylanguagetool: error: unrecognized arguments: folder/second-file.md`. The first file is not mentioned in the error message, only from the second file onwards.
